# Generated by Django 3.1.3 on 2022-04-12 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeeds', '0002_auto_20220407_2122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsfeed',
            options={'ordering': ('user', '-created_at')},
        ),
    ]
